### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined in TodoMVC

### ISSUE THREAD

**Issue by rusco** [vuejs/rc.vuejs.org#1]
Going to http://rc.vuejs.org/examples/todomvc.html
(latest Chrome/Win7, 64 bit) I get  2 errors in the console:

Uncaught TypeError: Cannot read property 'get' of undefined, vue.js l. 9379
and
Uncaught ReferenceError: app is not defined, routes.js, l, 24.

May be just a packaging problem .

**Comment by yyx990803** [comment]
Thanks, fixed.
